services:
  tracker:
    container_name: tracker
    image: tradestracker
    build:
      context: .
      dockerfile: TradesTracker/Dockerfile
    configs:
     - source: app_config
       target: app/config.json

configs:
  app_config:
    file: TradesTracker/config.json
